- name: add download.docker.com to trust cert
  shell: /home/solon/trust_cert.sh download.docker.com 443
  become: true
  become_user: root

- name: update /etc/apt/sources.list.d/docker.list
  template:
    src: docker.list
    dest: /etc/apt/sources.list.d/docker.list
  become: true
  become_user: root

- name: "Add a gpg key, from download.docker.com"
  apt_key:
    # url: http://mirrors.aliyun.com/docker-ce/linux/ubuntu/gpg
    url : https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true
  become_user: root

- name: install docker-ce
  apt:
    name: docker-ce=17.03.2~ce-0~ubuntu-xenial
    force: true
    update_cache: true
  become: true
  become_user: root
  notify:
    - restart Docker
    - test Docker
