---

- set_fact: cluster_join_script={{ hostvars[groups['kube-master'][0]]['cluster_join_script'] }}

- name: Join kubernetes cluster
  shell: echo '' | {{ cluster_join_script }}
  when: cluster_join_script is defined